/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bunong.view;

//import static com.bunong.view.Window.HEIGHT;
//import static com.bunong.view.Window.WIDTH;
//import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author zikrurridhoafwani
 */
public class UsernamePanel extends javax.swing.JPanel implements Runnable {

    static String username;    

    public UsernamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        start.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        start.setText("START");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        add(start);
        start.setBounds(343, 502, 140, 50);

        userNameField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userNameField.setText("Username...");
        userNameField.setHorizontalAlignment(JTextField.CENTER);
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        add(userNameField);
        userNameField.setBounds(275, 270, 250, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_userNameFieldActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startActionPerformed
        System.out.println("button clicked");
        Game game = new Game();
        Window.frame.getContentPane().removeAll();
        Window window = new Window(WIDTH, HEIGHT, "Bunong Game", game);
        username = userNameField.getText();
        System.out.println("username loaded");
    }// GEN-LAST:event_startActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton start;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Music music = new Music();
        music.loadMusic(music.filepath2);
        music.clip.start();
    }
}